[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
license = "MIT"
name = "rrrocket"
repository = "https://github.com/nickbabcock/boxcars"
version = "0.5.1-pre"
publish = false
description = "Rocket League Replay parser to JSON CLI app"
edition = "2018"

[dependencies]
snafu = "0.5.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.3"
rayon = "1"
boxcars = "0.5"
glob = "0.3"
either = "1"

[dev-dependencies]
assert_cmd = "0.11"
predicates = "1"
fs_extra = "1"
tempfile = "3"
