[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
license = "MIT"
name = "rrrocket"
repository = "https://github.com/nickbabcock/boxcars"
version = "0.2.10"
publish = false
description = "Rocket League Replay parser to JSON CLI app"

[dependencies]
failure = "0.1.1"
serde_json = "1.0.6"
structopt = "0.2"
rayon = "0.9"
boxcars = "0.2.8"
globset = "0.2"

[dev-dependencies]
assert_cmd = "0.11"
predicates = "1"
