[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
license = "MIT"
name = "rrrocket"
repository = "https://github.com/nickbabcock/boxcars"
version = "0.1.0"

[dependencies]
error-chain = "0.11.0"
serde_json = "1.0.6"
structopt = "0.1.5"
structopt-derive = "0.1.5"

[dependencies.boxcars]
path = ".."
version = "0.1"
